version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - chmod +x ./devops/buildspec.sh
      - ./devops/buildspec.sh
artifacts:
  files:
    - '**/*'
